# Generated by Django 5.1.2 on 2024-10-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_type', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10)),
                ('prerequisites', models.TextField()),
            ],
        ),
    ]
